export const homeContent = {
  hero: {
    title: "Tunisia Trust Engine",
    subtitle: "Reduce RTO with AI-powered verification.",
  },
};

export const appContent = {
  appName: "Tunisia Trust Engine",
  supportEmail: "support@tte.tn",
  dashboard: {
    brandName: "Tunisia Trust Engine",
    pageTitle: "لوحة التحكم",
    pageSubtitle: "كل ما تحتاجه اليوم في مكان واحد.",
    loadingText: "جاري تحميل لوحة التحكم...",
    errorText: "تعذر تحميل البيانات. حاول مرة أخرى.",
    merchantBadge: "حساب التاجر",
    cards: {
      totalOrders: "إجمالي الطلبات",
      successRate: "نسبة النجاح",
      rto: "RTO",
      revenue: "الإيرادات",
      quickActions: "إجراءات سريعة",
      recentOrders: "آخر الطلبات",
      noOrders: "لا توجد طلبات بعد.",
      riskSummary: "ملخص المخاطر",
      lowRiskOrders: "طلبات منخفضة المخاطر",
      needsReview: "طلبات تحتاج مراجعة",
      tip: 'نصيحة: استخدم التحقق التلقائي لتقليل المرتجعات',
    },
    quickActions: [
      { id: "phone-verification", label: "تحقق من رقم", path: "/phone-verification" },
      { id: "reports", label: "إضافة تقرير", path: "/reports" },
      { id: "plugins", label: "إدارة الإضافات", path: "/plugins" },
      { id: "analytics", label: "الإحصائيات", path: "/analytics" },
    ],
    menuGroups: [],
  },
  settings: {
    pageTitle: "الإعدادات",
    pageSubtitle: "الملف الشخصي، مفتاح API، والإعدادات التلقائية",
    loadingText: "جاري التحميل...",
    profileTab: "الملف الشخصي",
    automationTab: "الإعدادات التلقائية",
    apiTab: "مفتاح API",
  },
  plugins: { pageTitle: "الإضافات" },
  reports: { pageTitle: "التقارير" },
  orders: { pageTitle: "الطلبات" },
  login: { pageTitle: "تسجيل الدخول" },
  register: { pageTitle: "التسجيل" },
  phoneVerification: { pageTitle: "التحقق من الهاتف" },
  forgotPassword: { pageTitle: "نسيت كلمة المرور" },
  credits: { pageTitle: "الاعتمادات" },
  support: { pageTitle: "الدعم" },
  referrals: { pageTitle: "الإحالات" },
  analytics: { pageTitle: "الإحصائيات" },
  subscription: { pageTitle: "الاشتراك" },
};
